---
name: 'Build and push a docker image'
on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Docker image name'
        required: true
        default: 'hello-world-node'
      tag:
        description: 'Docker image tag'
        required: false
        default: 'latest'
jobs:
  build_docker_image:
    name: 'Build docker image'
    runs-on: ubuntu-latest
    steps:
      - name: 'Check out the repository'
        uses: actions/checkout@v2
      - name: 'Set up QEMU'
        uses: docker/setup-qemu-action@v1
      - name: 'Set up Docker Buildx'
        uses: docker/setup-buildx-action@v1
      - name: 'Login to Dockerhub'
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USER_ID }}
          password: ${{ secrets.DOCKERHUB_USER_PASSWORD }}
      - name: 'Build and push'
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ secrets.DOCKERHUB_USER_ID }}/node-simple:'latest'
      - name: 'Image digest'
        run: echo ${{ steps.docker_build.outputs.digest }}