---
name: 'Build and push a docker image'
on:
  workflow_dispatch:
    inputs:
      user:
        description: 'Docker hub user name'
        required: true
        default: 'none'
      name:
        description: 'Docker image name'
        required: true
        default: 'hello-world-node'
      tag:
        description: 'Docker image tag'
        required: false
        default: 'latest'
jobs:
  build_docker_image:
    name: 'Build docker image'
    runs-on: ubuntu-latest
    steps:
      - name: 'Check out the repository'
        uses: actions/checkout@v2
      - name: 'Set up QEMU'
        uses: docker/setup-qemu-action@v1
      - name: 'Set up Docker Buildx'
        uses: docker/setup-buildx-action@v1
      - name: 'Login to Dockerhub'
        uses: docker/login-action@v1
        with:
          # optional (by default empty for docker hub)
          #registry: docker.pkg.github.com
          username: ${{ secrets.DOCKERHUB_USER_ID }}
          password: ${{ secrets.DOCKERHUB_USER_PASSWORD }}
      - name: 'Build and push'
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile          
          tags: ${{ github.event.inputs.user }}/node-simple:latest
          push: true
      - name: 'Image digest'
        run: echo ${{ steps.docker_build.outputs.digest }}